### ISSUE TITLE
Typos & small grammar inconsistencies in chapter 6 "UX matters"

### ISSUE THREAD

**Issue by frankschmitt** [ThinkR-open/building-shiny-apps-workflow#100]
I noticed a couple of typos and small grammar inconsistences. You'll find the list below, pull request incoming :-)

"can deserve you on the long run":  "deserve" feels wrong here. Also, I believe "in the long run" to be more idiomatic. I'd suggest "can hurt you in the long run"

"want the app to be useable": Typo: useable -> usable

"read complexe manuals": Typo: complexe -> complex

"You don't want your app to be one of that.": I think "one of that" should be "one of them"

"don't add feature for the sake of adding a feature.": I'd add an "a" in the first part: "don't add a feature for the sake of adding a feature."

"by the broader audience possible": I think the superlative is more idiomatic, therefore: broader -> broadest

"Web Accessibility is pretty standard concept": there's an a missing -> "Web Accessibility is a pretty standard concept"

"people w/ parkinson for example": I think parkinson should be uppercase (since it's a name), therefore parkinson -> Parkinson

**Comment by ColinFay** [comment]
Thanks!
