### ISSUE TITLE
Typo in Golem chapter

### ISSUE THREAD

**Issue by kdaily** [ThinkR-open/building-shiny-apps-workflow#107]
https://github.com/ThinkR-open/building-shiny-apps-workflow/blob/master/golem.Rmd#L15

Reads: 

We advice to use `{golem}` if you plan on following the workflow described in this book, but of course the workflow will still be valid of you plan on not using `{golem}`.

Should read:

"We **advise** to use `{golem}` if you plan on following the workflow described in this book, but of course the workflow will still be valid **if** you plan on not using `{golem}`."

**Comment by ColinFay** [comment]
Thanks!
