### ISSUE TITLE
Typos in subsection 1.2.1

### ISSUE THREAD

**Issue by urslaan-youhan** [ThinkR-open/building-shiny-apps-workflow#124]
https://thinkr-open.github.io/building-shiny-apps-workflow/successfulshinyapp.html#reaching-the-cliff-of-complexity

Sentence reads: "Getting a clear definition is not an easy task2 as it very depends on who is concerned and who you are talking to."

It should read: "Getting a clear definition is not an easy task2 as it very **much** depends on who is concerned and who you are talking to."

Sentence reads: "But let us try to come with a definition..."

It should read: "But let us try to come **up** with a definition..."

**Comment by statnmap** [comment]
Thank you for your contribution, we will correct these typos in the next update.
