### ISSUE TITLE
3.24.3 Typo

### ISSUE THREAD

**Issue by cedricbriandgithub** [ThinkR-open/building-shiny-apps-workflow#127]
Similarly to the “stratégie du petit r”, we can create an R6 object which is pass along the modules. This R6 object is not a reactive object, making it more robust to the complexity of handling reactivity invalidation across modules.

=> which is **passed**
" it more robust to the complexity of handling reactivity invalidation across modules"
you might want to rephrase this complex sentence

**Comment by statnmap** [comment]
Thank you. I rephrased the sentence as is:  
> Similarly to the "stratégie du petit r", we can create an R6 object, which is passed along the modules. 
This R6 object is not a reactive object.
This reduces reactivity of the application, thus reduces the complexity of handling chain reactions across modules.  

This will be modified in a coming commit.
