### ISSUE TITLE
Rewrite the "intro to golem" chapter

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/building-shiny-apps-workflow#18]
https://github.com/ThinkR-open/building-shiny-apps-workflow/blob/master/golem.Rmd

The elements right now are copied and pasted from other elements. The introduction to `{golem}` here should be re-written.

**Comment by statnmap** [comment]
I assume that you already did that issue as it is checked in the META. I will review it latter but we can close this issue.
