### ISSUE TITLE
"Big"

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/building-shiny-apps-workflow#41]
Change the term "big" to sthg else like "production" / "successful", etc...

**Comment by ColinFay** [comment]
I also like "large scale", but I think the "successful" adjective is the work we should use - we don't care about the size, we care that it will be a successful project.

**Comment by ColinFay** [comment]
http://www.catb.org/~esr/writings/taoup/html/complexitychapter.html

**Comment by ColinFay** [comment]
> Most software is fragile and buggy because most programs are too complicated for a human brain to understand all at once. When you can't reason correctly about the guts of a program, you can't be sure it's correct, and you can't fix it if it's broken.

http://www.catb.org/~esr/writings/taoup/html/ch01s06.html

**Comment by ColinFay** [comment]
I like the notion of "Complex" / "Complexity" the way it's used in [Chapter 13. Complexity](http://www.catb.org/~esr/writings/taoup/html/complexitychapter.html)

**Comment by ColinFay** [comment]
"robust"

**Comment by DianeBeldame** [comment]
> One of the defining characteristics of a complex system is that it defies any single person's ability to see the system as a whole and understand how all the pieces fit together. Complex system typically have a high degree of interconnectedness of tightly coupled components, and system-level behavior cannot be explained merely in terms of the behavior of the system components 

The DevOps Handbook - p 27-28

**Comment by DianeBeldame** [comment]
See also "Rugged computing" movement : https://ruggedsoftware.org/

> “Rugged” describes software development organizations that have a culture of rapidly evolving their ability to create available, survivable, defensible, secure, and resilient software.
