### ISSUE TITLE
Add autobuild throught travis

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/building-shiny-apps-workflow#58]
The book should be auto built with travis whenever we push to master

**Comment by ColinFay** [comment]
https://bookdown.org/yihui/bookdown/github.html

**Comment by statnmap** [comment]
Auto-build in `docs/wip`: https://github.com/ThinkR-open/building-shiny-apps-workflow/pull/77
Manual build for stable version: https://github.com/ThinkR-open/building-shiny-apps-workflow/pull/78
